### ISSUE TITLE
life raft "O" not displaying in Chrome for Android

### ISSUE THREAD

**Issue by rahobbs** [econchick/newcoder.io#1]
Instead, I get "New C der" in Chrome on my SIII. Everything is A-ok in Chrome on my Linux box and in Firefox for Android.

**Comment by econchick** [comment]
ahh hmm. okay; not much of a mobile person but thank you for letting me know - should figure out how to work this! :D

**Comment by rahobbs** [comment]
Looks like this can be closed.
