### ISSUE TITLE
Google Maps link not working

### ISSUE THREAD

**Issue by rodney757** [econchick/newcoder.io#2]
On this page http://newcoder.io/Part-3-Map/, the link for google maps is taking me to http://newcoder.io/Part-3-Map/maps.google.com instead of maps.google.com. The link looks correct on the source page when I inspect the element. I'm using Firefox 19.0.2 on osx

**Comment by econchick** [comment]
Addressed at https://github.com/econchick/new-coder/pull/33 - thank you!
