### ISSUE TITLE
How can we use the source and files?

### ISSUE THREAD

**Issue by karan** [econchick/newcoder.io#5]
What license is used for newcoder source? How can we reuse the source of the website, the text and the source of the tutorial itself?

**Comment by econchick** [comment]
Hi @thekarangoel - the code is under [zlib/libpng license](http://opensource.org/licenses/Zlib) and the tutorial language that is on newcoder.io (under docs/ folder in the new-coder repo) is under the [Creative Commons Attribution-ShareAlike 3.0 Unported License](http://creativecommons.org/licenses/by-sa/3.0/deed.en_US).

HTH! reopen the issue if you have more questions.

**Comment by econchick** [comment]
I forgot to mention - the "real" repo is at github.com/econchick/new-coder where code, tutorial language, and licenses live.

**Comment by karan** [comment]
Great. Thanks for the clarification!
